version: '3'
services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ${APP_NAME:?err}-php
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        volumes:
            - '${WORK_DIRECTORY}/src:/var/www/html'
            - '${WORK_DIRECTORY}/config/php/local.ini:/usr/local/etc/php/conf.d/local.ini'
        networks:
            - app-network    

    nginx:
        image: nginx:latest
        container_name: ${APP_NAME:?err}-nginx
        ports:
            - '80:80'
        links:
            - 'php'
        volumes:
            - '${WORK_DIRECTORY}/src:/var/www/html'
            - '${WORK_DIRECTORY}/config/nginx:/etc/nginx/conf.d'
        networks:
            - app-network

    mariadb:
        image: mariadb:10.5
        container_name: ${APP_NAME:?err}-mariadb
        restart: 'on-failure'
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE:?err}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - '${WORK_DIRECTORY}/mysql:/var/lib/mysql'
        networks:
          - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge